#!/bin/bash

set -euo pipefail

#=============================================================================
# setup notes
#=============================================================================
# this builds variations of the vcs simulator for your project

#DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$DIR/../../sourceme.sh"

# from lab2
CONFIG_BASE=GemminiEE290Lab3RocketConfig

BIN_BASE="$DIR/simv-example-${CONFIG_BASE}"

# for selective printfs (see Makefile)
export ENABLE_PRINTF_PATTERN='.*\"cycle.*entry.*(accept|issue|final)\[.*'

#=============================================================================
# subroutines
#=============================================================================
err() { echo "[ERROR]: $@"; exit 1; }
info() { echo "[INFO]: $@"; }

#=============================================================================
# configuration
#=============================================================================
cd "$DIR"

if [ $# -ne 1 ] ; then err "usage: $0 <base>" ; fi
case $1 in
  base) 
    rm -f "$BIN_BASE"
    make CONFIG=$CONFIG_BASE
    info "finished building $CONFIG_BASE"
    ;;
  *) 
    err "invalid option: $1"
    ;;
esac
